# Numpy


In [1]:
import numpy as np


In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

**Two Dimentional Array**


In [23]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.size
#6 elements

6

In [25]:
a.itemsize
#int data type size


4

In [26]:
a.shape
#Dimention in row , column

(2, 3)

# Change Data type of array

In [27]:
a.dtype

dtype('int32')

In [28]:
a = np.array([[1,2,3],[4,5,6]] , dtype =np.float64)
a
# change data type of array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
a.dtype

dtype('float64')

In [30]:
a = np.array([[1,2,3],[4,5,6]] , dtype =complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

# Initialize array


In [31]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
a = np.ones((3,3,))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [37]:
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Change Shapa of array

In [39]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [41]:
a.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
a.ravel()
#Flat the array

array([1, 2, 3, 4, 5, 6])

In [47]:
a


array([1, 2, 3, 4, 5, 6])

In [50]:
a  = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

# Math functions

In [51]:
a.sum()

21

In [52]:
a.min()

1

In [60]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a.max()

6

In [57]:
a.shape

(3, 2)

In [58]:
a.sum(axis=0)
#column wise sum

array([ 9, 12])

In [61]:
a.sum(axis=1)
#Row wise sum

array([ 3,  7, 11])

In [62]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [63]:
np.std(a)

1.707825127659933

# Two array operation

In [64]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
b = np.arange(7,13)
b = b.reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [80]:
a+b

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [82]:
b-a

array([[6, 6],
       [6, 6],
       [6, 6]])

In [83]:
a*b

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [84]:
a/b

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [86]:
b//a

array([[7, 4],
       [3, 2],
       [2, 2]], dtype=int32)

# Slicing 


In [90]:
a  = np.array([[6,3, 5] , [4,6,7],[9,7,4]])
a

array([[6, 3, 5],
       [4, 6, 7],
       [9, 7, 4]])

In [92]:
a[1,:]

array([4, 6, 7])

In [93]:
a[1:,:]

array([[4, 6, 7],
       [9, 7, 4]])

In [94]:
a[1:,1:]

array([[6, 7],
       [7, 4]])

# Iterate array
    

In [95]:
for row in a:
    print(row)

[6 3 5]
[4 6 7]
[9 7 4]


In [96]:
for cell in a.flat:
    print(cell)

6
3
5
4
6
7
9
7
4


In [106]:
b = np.arange(6,15).reshape(3,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [108]:
a

array([[6, 3, 5],
       [4, 6, 7],
       [9, 7, 4]])

In [110]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [115]:
np.vstack((a,b))

array([[ 6,  3,  5],
       [ 4,  6,  7],
       [ 9,  7,  4],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [118]:
np.hstack((a,b))

array([[ 6,  3,  5,  6,  7,  8],
       [ 4,  6,  7,  9, 10, 11],
       [ 9,  7,  4, 12, 13, 14]])

In [121]:
c = np.arange(1,19).reshape(2,9)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [124]:
result = np.hsplit(c,3)
result

[array([[ 1,  2,  3],
        [10, 11, 12]]),
 array([[ 4,  5,  6],
        [13, 14, 15]]),
 array([[ 7,  8,  9],
        [16, 17, 18]])]

In [125]:
result[0]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [126]:
result[1]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [128]:
c= c.reshape(9,2)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [130]:
result = np.vsplit(c,3)
result

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[13, 14],
        [15, 16],
        [17, 18]])]

In [134]:
result[0][:2]

array([[1, 2],
       [3, 4]])

# Indexing with boolean array

In [137]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
b = a>4
b
#all the element which is greater then 4 is true

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [142]:
a[b]
#it will return all the element which is greater then 4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
a[b] = -1
a

array([[ 1,  2,  3,  4],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])